package com.vajasoft.classfilescanner;

import com.vajasoft.classfile.ClassFile;
import com.vajasoft.wizard.Wizard;
import com.vajasoft.wizard.WizardCard;
import com.vajasoft.zup.ZupTableModel;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.*;
import java.util.logging.Logger;
import java.util.zip.*;
import javax.swing.*;

import javax.swing.table.TableRowSorter;

/**
 *
 * @author  z705692
 */
public class WizCardArchive extends javax.swing.JPanel implements WizardCard {

    private static final Logger LOGGER = Logger.getLogger(WizCardArchive.class.getPackage().getName());
    private final Wizard<Property> wizard;
    private final ZupTableModel archiveModel = new ZupTableModel();
    private final ArchivePropertyListener archivePropListener = new ArchivePropertyListener();

    public WizCardArchive(Wizard<Property> wiz) {
        initComponents();
        Util.setListSelectionListeners(lstContents, cmdNext);
        wizard = wiz;
        wizard.addPropertyChangeListener(Property.ARCHIVE, archivePropListener);
    }

    @Override
    public void init() {
        LOGGER.fine("WizCardArchive inited");
    }

    @Override
    public void activate() {
        LOGGER.fine("WizCardArchive activated");
        getRootPane().setDefaultButton(cmdNext);
        lstContents.requestFocusInWindow();
        wizard.setProperty(Property.CLASS_FILE, null);
    }

    @Override
    public void passivate() {
        LOGGER.fine("WizCardMembers passivated");
    }

    private class ArchivePropertyListener implements PropertyChangeListener {
        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            archiveModel.setFile(null);
            ZipFile zf = (ZipFile) evt.getNewValue();
            if (zf != null) {
                archiveModel.setFile(zf);
                fldArchive.setText(zf.getName());
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArchive = new javax.swing.JLabel();
        fldArchive = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstContents = new javax.swing.JTable();
        cmdPrev = new javax.swing.JButton();
        cmdNext = new javax.swing.JButton();

        setName("ARCHIVE"); // NOI18N

        lblArchive.setText("<html>\n    <font style=\"font-size: 14pt; color:maroon; font-weight: bold\">\n        2. What to scan for (cont'd)\n    </font>\n    <br>\n    <br>\n    Select a class from the archive:\n</html>\n");

        fldArchive.setText("-----");

        lstContents.setModel(archiveModel);
        lstContents.setName("focus"); // NOI18N
        lstContents.setRowSorter(new TableRowSorter(archiveModel));
        jScrollPane2.setViewportView(lstContents);

        cmdPrev.setMnemonic('p');
        cmdPrev.setText("<< Previous");
        cmdPrev.setMaximumSize(new java.awt.Dimension(98, 23));
        cmdPrev.setMinimumSize(new java.awt.Dimension(98, 23));
        cmdPrev.setPreferredSize(new java.awt.Dimension(98, 23));
        cmdPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrevActionPerformed(evt);
            }
        });

        cmdNext.setMnemonic('n');
        cmdNext.setText("Next >>");
        cmdNext.setMaximumSize(new java.awt.Dimension(98, 23));
        cmdNext.setMinimumSize(new java.awt.Dimension(98, 23));
        cmdNext.setName("default"); // NOI18N
        cmdNext.setPreferredSize(new java.awt.Dimension(98, 23));
        cmdNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblArchive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                            .addComponent(fldArchive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArchive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldArchive)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextActionPerformed
        int rowInView = lstContents.getSelectedRow();
        if (rowInView >= 0) {
            try {
                java.util.zip.ZipFile zf = (java.util.zip.ZipFile) wizard.getProperty(Property.ARCHIVE);
                java.util.zip.ZipEntry ze = archiveModel.getValue(lstContents.convertRowIndexToModel(rowInView));
                ClassFile cf = new ClassFile(zf.getInputStream(ze));
                wizard.setProperty(com.vajasoft.classfilescanner.Property.CLASS_FILE, cf);
                wizard.nextPhase();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Invalid file", JOptionPane.ERROR_MESSAGE);
            }
        } else {
        }
    }//GEN-LAST:event_cmdNextActionPerformed

    private void cmdPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrevActionPerformed
        wizard.previousPhase();
    }//GEN-LAST:event_cmdPrevActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdNext;
    private javax.swing.JButton cmdPrev;
    private javax.swing.JLabel fldArchive;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArchive;
    private javax.swing.JTable lstContents;
    // End of variables declaration//GEN-END:variables
}
