/*
 * WizCardSummary.java
 *
 * Created on 13. kesäkuuta 2007, 10:02
 */

package classfilescanner;

import java.io.*;
import java.util.*;

import classfile.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.logging.Logger;
import wizard.*;


/**
 *
 * @author  z705692
 */
public class WizCardSummary extends javax.swing.JPanel implements WizardCard {
    private static final Logger logger = Logger.getLogger(WizCardSummary.class.getPackage().getName());
    private Wizard<Property> wizard;
    private ReferenceTableModel referenceListModel = new ReferenceTableModel();
    private ReferencePropertyListener refPropListener = new ReferencePropertyListener();
    private RootFilePropertyListener rootFilePropListener = new RootFilePropertyListener();
    
    public WizCardSummary(Wizard<Property> wiz) {
        initComponents();
        wizard = wiz;
        wizard.addPropertyChangeListener(Property.REFERENCES, refPropListener);
        wizard.addPropertyChangeListener(Property.ROOT_FILE, rootFilePropListener);
    }

    public void init() {
        logger.fine("WizCardSummary inited");
    }

    public void activate() {
        logger.fine("WizCardSummary activated");
        getRootPane().setDefaultButton(cmdScan);
        cmdScan.requestFocusInWindow();
    }
    
    public void passivate() {
        logger.fine("WizCardSummary passivated");
    }

    private class ReferencePropertyListener implements PropertyChangeListener {
        public void propertyChange(PropertyChangeEvent evt) {
            referenceListModel.clearData();
            Collection<Reference> refs = (Collection<Reference>)evt.getNewValue();
            if (refs != null) {
                referenceListModel.addData(refs);
            }
        }
    }

    private class RootFilePropertyListener implements PropertyChangeListener {
        public void propertyChange(PropertyChangeEvent evt) {
            File root = (File)evt.getNewValue();
            String r = root != null ? root.getAbsolutePath() : "";
            fldSummaryRoot.setText(r);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSummaryRoot = new javax.swing.JLabel();
        fldSummaryRoot = new javax.swing.JLabel();
        lblSummaryReferences = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSummaryReferences = new javax.swing.JTable();
        cmdPrev = new javax.swing.JButton();
        cmdScan = new javax.swing.JButton();

        setName("SUMMARY"); // NOI18N

        lblSummaryRoot.setText("<html><font style=\"font-size: 14pt; color:maroon; font-weight: bold\">3. Summary</font>\n<br>\n<br>\nScan from:\n</html>\n");
        lblSummaryRoot.setFocusable(false);

        fldSummaryRoot.setText("-----");
        fldSummaryRoot.setFocusable(false);

        lblSummaryReferences.setText("Search refererences to:");
        lblSummaryReferences.setFocusable(false);

        jScrollPane1.setName("focus"); // NOI18N

        lstSummaryReferences.setModel(referenceListModel);
        jScrollPane1.setViewportView(lstSummaryReferences);

        cmdPrev.setMnemonic('p');
        cmdPrev.setText("<< Previous");
        cmdPrev.setMaximumSize(new java.awt.Dimension(98, 23));
        cmdPrev.setMinimumSize(new java.awt.Dimension(98, 23));
        cmdPrev.setPreferredSize(new java.awt.Dimension(98, 23));
        cmdPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrevActionPerformed(evt);
            }
        });

        cmdScan.setMnemonic('s');
        cmdScan.setText("Scan");
        cmdScan.setMaximumSize(new java.awt.Dimension(98, 23));
        cmdScan.setMinimumSize(new java.awt.Dimension(98, 23));
        cmdScan.setName("default"); // NOI18N
        cmdScan.setPreferredSize(new java.awt.Dimension(98, 23));
        cmdScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdScanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSummaryRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSummaryReferences)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(fldSummaryRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSummaryRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fldSummaryRoot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSummaryReferences)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void cmdScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdScanActionPerformed
    wizard.nextPhase();
}//GEN-LAST:event_cmdScanActionPerformed

private void cmdPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrevActionPerformed
    wizard.previousPhase();
}//GEN-LAST:event_cmdPrevActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdPrev;
    private javax.swing.JButton cmdScan;
    private javax.swing.JLabel fldSummaryRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSummaryReferences;
    private javax.swing.JLabel lblSummaryRoot;
    private javax.swing.JTable lstSummaryReferences;
    // End of variables declaration//GEN-END:variables
    
}
